# Generated by Django 3.2.4 on 2021-06-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Accounts',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_username', models.CharField(max_length=63, unique=True)),
                ('_password', models.CharField(max_length=255)),
                ('_reg_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
