# Generated by Django 3.2.4 on 2021-06-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='_status',
            field=models.IntegerField(default=0),
        ),
    ]
