# Generated by Django 3.2.4 on 2021-06-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0002_rename_admin_accounts_adminaccounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminAccounts',
            new_name='admin_accounts',
        ),
    ]
