# Generated by Django 3.2.4 on 2021-06-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0002_userinfo__status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='_name',
        ),
    ]
