# Generated by Django 3.2.4 on 2021-06-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0003_remove_userinfo__name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='_contact',
            field=models.IntegerField(),
        ),
    ]
