# Generated by Django 3.2.4 on 2021-06-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0003_rename_adminaccounts_admin_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_accounts',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_name', models.CharField(max_length=63)),
                ('_email', models.CharField(max_length=63, unique=True)),
                ('_contact', models.CharField(max_length=10)),
                ('_password', models.CharField(max_length=255)),
                ('_status', models.IntegerField(default=0)),
                ('_reg_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
