# Generated by Django 3.2.4 on 2021-06-25 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wsite', '0004_alter_userinfo__contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
