# Generated by Django 3.2.4 on 2021-06-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0008_auto_20210626_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=models.IntegerField(blank=True),
        ),
    ]
