# Generated by Django 3.2.4 on 2021-06-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0009_alter_userinfo_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
