# Generated by Django 3.2.4 on 2021-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0010_alter_userinfo_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
